/*
 * sensor_config.h
 *
 *  Created on: 01.12.2021
 *      Author: Ryan
 */

#ifndef INC_SENSOR_CONFIG_H_
#define INC_SENSOR_CONFIG_H_

#define CONFIG_BNO_ACCEL_OFFSET_X 11
#define CONFIG_BNO_ACCEL_OFFSET_Y 1
#define CONFIG_BNO_ACCEL_OFFSET_Z 79
#define CONFIG_BNO_ACCEL_OFFSET_R 1000

#define CONFIG_BNO_GYRO_OFFSET_X -2
#define CONFIG_BNO_GYRO_OFFSET_Y 2
#define CONFIG_BNO_GYRO_OFFSET_Z 3

#define CONFIG_BNO_MAG_OFFSET_X -3
#define CONFIG_BNO_MAG_OFFSET_Y -7
#define CONFIG_BNO_MAG_OFFSET_Z 1
#define CONFIG_BNO_MAG_OFFSET_R 983

#endif /* INC_SENSOR_CONFIG_H_ */
